# Generated by Django 5.1.6 on 2025-02-17 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_rep', models.CharField(max_length=100)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('resolution', models.TextField(blank=True, null=True)),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='requests.servicerequest')),
            ],
        ),
    ]
