# Generated by Django 5.1.6 on 2025-02-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_supportticket_service_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportticket',
            old_name='resolution',
            new_name='resolution_notes',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='support_rep',
        ),
        migrations.AddField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='service_request',
            field=models.TextField(),
        ),
    ]
